feature/opixxx step1 PR
C4-ComeTrue/C4-Preflight-2425 pull request #1
Opened 2024-10-18 06:30 UTC by opixxx

-  이베일 발송 기능 구현

- 분단위 메일 전송을 구현하기 위해서 메일 전송 요청을 받아 메일 전송을 PENDING 상태로 DB에 저장합니다.
- @Scheduled 어노테이션을 이용해서 분단위로 PENDING 상태의 MailArchive을 가져와 반복문을 돌며 메일을 전송합니다.
     - 메일 성공적으로 전송된 MailArchive의 상태를 SENT로 변경합니다.
     - 메일 전송이 실패할 경우 MailArchive의 상태를 FAIL로 변경합니다.

- 메일 전송이 실패한 요청 처리 방법

- "/re-send" API를 하나 더 만들어서 전송 실패한 MailArchive를 재전송하는 기능을 만들었습니다.
- 계좌 상품 설명서라는 것이 사용자 입장에서 계좌를 생성하자마자 읽을 정도로 중요한 메일은 아니라고 생각하여, 관리자가 메일 전송 실패 로그를 보고 직접 수동으로 요청하는 방법으로 구현했습니다.

2024-10-18 13:38 UTC, VSFe requested changes
ㄲㄲ

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/config/MailConfig.java
> +        props.put("mail.debug", "true");
debug를 하드코딩하는건 썩 좋은 생각이 아니네요.

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/controller/MailController.java
> +        return ResponseEntity.ok().build();
응답이 없으면 NO_CONTENT (204) 가 더 낫지 않을까요?

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/domain/repository/MailRepository.java
> +    List<MailArchive> findMailArchiveByMailStatus(MailStatus status);
이런 쿼리는 굳이 `@Query` 를 사용하지 않아도, 본래 조건을 통해 조회해도 동일한 결과가 나옴이 보장되는지라...
굳이 사용할 필요가 없어보입니다.

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/dto/MailRequest.java
> +        String email,
이메일 주소로 "" 이 주어질 수 있겠네요.

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/dto/MailRequest.java
> +        Long accountId,
accountId가 음수일 수 있을까요?

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/dto/MailRequest.java
> +        String content
공백 20글자로도 메일 전송이 가능할까요?

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +        List<MailArchive> pendingMail = mailRepository.findMailArchiveByMailStatus(PENDING);
`PENDING` 상태로 남은 메일의 수가 5000개라고 가정해 봅시다.
괜찮은 쿼리일까요?

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +        log.info("메일 전송 실행");
일반적으로 개발 환경에서는 log level을 debug로, 운영 환경에서는 info/warn 수준으로 설정합니다.

운영 환경에서 해당 요청이 들어올 "때 마다" 해당 로그가 출력되게 되면, 에러 디버깅 과정에서 매우 번거로워질 확률이 높습니다.

개발 과정에서의 디버깅용인지, 운영 환경에서 실제로 필요한 로그인지 잘 생각해보시고 로그 레벨을 지정하는게 좋습니다.

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +        List<MailArchive> failMail = mailRepository.findMailArchiveByMailStatus(FAIL);
단순 네트워크 이슈로 전송이 안 된 케이스도 있어서... 실제로는 저희가 대응해야 할 문제가 많지는 않습니다.
새벽 시간대에 전송이 실패하면, 사람이 일어나서 대응해야 하는 것도 다소 어색하고요.

그냥 전송할 때 묶어서 하면 되지 않을까요?

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +                log.error("메일 전송 실패");
에러도 같이 로깅하게 해주세요.
```java
log.error("메일 전송 실패", e);
```

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/domain/MailArchive.java
> +        this.sentTime = LocalDateTime.now();
`changeStatusSent` 와 분리되어서 호출될 케이스가 없어보이는데, 하나의 메서드로 묶는게 낫지 않을까요?

2024-10-18 13:38 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/domain/MailArchive.java
> +    private String content;
content도 non-null 로 보이는데...

2024-10-18 14:58 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/controller/MailController.java
> +        return ResponseEntity.ok().build();
NO_CONTENT 가 있었네요,,, 수정했습니다

2024-10-18 14:59 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/domain/MailArchive.java
> +        this.sentTime = LocalDateTime.now();
네 그렇네요 묶는게 훨씬 더 나아보입니다

2024-10-18 16:02 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/dto/MailRequest.java
> +        Long accountId,
그렇네요.. Positive 적용했습니다.

2024-10-18 16:02 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/dto/MailRequest.java
> +        String email,
@NotBlank 로 공백 체크와 @Email 로 이메일 형식 체크하도록 수정했습니다.

2024-10-18 16:03 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/dto/MailRequest.java
> +        String content
자꾸 공백 생각을 놓치네요,, @NotBlank 적용했습니다

2024-10-18 16:04 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +        List<MailArchive> pendingMail = mailRepository.findMailArchiveByMailStatus(PENDING);
100개씩 조회해오면서 한 스케쥴러에서 모두 처리하도록 수정했습니다.

2024-10-18 16:05 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +        log.info("메일 전송 실행");
그렇겠네요,, 디버깅용으로 설정한 로그라 debug로 수정했습니다.

2024-10-18 16:06 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/service/MailService.java
> +        List<MailArchive> failMail = mailRepository.findMailArchiveByMailStatus(FAIL);
네 일단 PENDING, FAIL 묶어서 조회했는데 FAIL 같은 경우 전송 시도횟수 같은 것을 체크해서 전송 횟수를 제한하도록 수정해보겠습니다.

2024-10-18 16:11 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/mail/domain/repository/MailRepository.java
> +    List<MailArchive> findMailArchiveByMailStatus(MailStatus status);
쿼리 내용이 좀 변경돼서 @Query 를 이용해서 작성했습니다.

2024-10-21 11:58 UTC, VSFe approved these changes

2024-10-21 15:01 UTC, merged