Feature/zzambas step1: 분 단위로 메일 전송
C4-ComeTrue/C4-Preflight-2425 pull request #2
Opened 2024-10-18 07:53 UTC by ZZAMBAs

## 개요
대용량 서버에서 계좌를 생성한 후, 백오피스 서버의 API를 호출해 메일을 저장하도록 하고, 백오피스 서버는 분 단위로 전송되어 있지 않은 메일을 전송합니다. 
![image](https://github.com/user-attachments/assets/9d0632cb-d353-4231-a610-5d9159b9a62f)

## 클래스 소개
핵심적인 클래스는 아래와 같습니다.
* `MailSender`
* * 메일을 실제로 전송하는 클래스
* `MailService`
* * `createMail()` : API로 계좌 id와 유저 id를 받고 발송할 메일을 저장하는 메서드
* * `sendMail()` : 1분마다 메일을 발송하는 메서드. `@Scheduled`를 이용하였고, DB 내 메일 중 보내지지 않은 메일을 최대 1000개까지 가져옵니다. 그리고 메일을 각각 전송한 뒤, 모든 전송된 메일의 전송 시각을 업데이트 처리합니다. 보내지지 않은 메일 판단은 `Mail`의 `sendTime`이 `NULL`인 경우입니다.

## 예외 상황에 대한 처리
* DB와 연결이 너무 늦거나 메일에 연결된 계좌 혹은 유저가 사실 없다면 메일은 저장되지 않을 것입니다.
* 메일 전송 중에 특정 메일에서 전송이 실패하는 예외가 일어난다면 처리를 중단하고 지금까지 보낸 메일에 대해서만 전송 시각을 업데이트 합니다. 예를 들어 메일 1, 2, 3을 전송하는데 2에서 예외가 나면 메일 1에 대해서만 전송 시각을 DB에 업데이트 합니다.

2024-10-18 13:51 UTC, VSFe requested changes
ㅎㅎ

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/global/config/MailSenderConfig.java
> +		properties.setProperty("mail.debug", "true");
debug를 하드코딩하는건 썩 좋지 않습니다.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/application/MailSender.java
> +			message.setText(mailInfoDto.getUserNickname() + "님, 계좌 생성이 완료되었습니다! \n생성 계좌: " + mailInfoDto.getAccountNumber());
해당 프로젝트는 JDK 17로 세팅되어 있습니다.
multiline string 으로 변경해 주세요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +		log.info("배치 작업 활성화");
일반적으로 개발 환경에서는 log level을 debug로, 운영 환경에서는 info/warn 수준으로 설정합니다.

운영 환경에서 해당 요청이 들어올 "때 마다" 해당 로그가 출력되게 되면, 에러 디버깅 과정에서 매우 번거로워질 확률이 높습니다.

개발 과정에서의 디버깅용인지, 운영 환경에서 실제로 필요한 로그인지 잘 생각해보시고 로그 레벨을 지정하는게 좋습니다.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +		List<MailInfoToSendDto> mailsToSend = mailRepository.findAllToSend(MAX_SEND_SIZE);
순간적인 트래픽으로 메일이 20000개 정도 쌓였다고 가정합시다.
현재 로직으로는 1회 호출에 1000개만 처리하므로, 메일이 쌓이게 되면 20분을 기다려야 하네요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/controller/MailController.java
> +		return ResponseEntity.ok(responseDto);
DB에 저장하여 리소스를 만들어내는 만큼, 이건 CREATED가 맞을 것 같이 보여요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/dto/CreateMailRequestDto.java
> +								   int accountId) {
?
형식 확인 부탁드려요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/infrastructure/MailJpaRepository.java
> +				UPDATE Mail m
형식 조정해 주세요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/infrastructure/MailJpaRepository.java
> +	@Query(value = """
잘못 들어간 데이터가 존재하거나, 메일 요청 생성 후 user나 account 데이터가 삭제되면,
해당 데이터는 영원히 메일 미전송 상태로 남아있겠네요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/infrastructure/MailJpaRepository.java
> +		JOIN account a ON a.account_id = m.account_id
메일 테이블에는 인덱스가 없네요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +		accountRepository.findById(requestDto.accountId()).orElseThrow(() -> new RuntimeException("해당 계좌를 찾을 수 없습니다."));
RuntimeException 을 던지기 때문에, 사용자의 잘못임에도 INTERNAL_SERVER_ERROR 가 던져지겠네요.

2024-10-18 13:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +			log.warn("마지막으로 발송된 메일 id: {}", sentMailIds.get(sentMailIds.size() - 1));
새벽에 예외가 하나 생기면, 그 이후 요청은 몇 시간 동안 처리가 안 되겠네요.
순차 처리하고 예외 발생하면 로깅만 하고 다음 값 처리를 진행하도록 해야할 것 같네요.

2024-10-18 15:23 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +		accountRepository.findById(requestDto.accountId()).orElseThrow(() -> new RuntimeException("해당 계좌를 찾을 수 없습니다."));
그렇다면 이런 상황에서는 400 에러를 내는 것이 좋은 걸까요?

2024-10-18 15:23 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +		log.info("배치 작업 활성화");
이전 프로젝트에서 아무 생각 없이 info로 날려서 디버깅 힘들었던 기억이 있긴 합니다

2024-10-18 15:23 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +		List<MailInfoToSendDto> mailsToSend = mailRepository.findAllToSend(MAX_SEND_SIZE);
다시 한 번 고민해 보겠습니다!

2024-10-18 15:23 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/application/MailService.java
> +			log.warn("마지막으로 발송된 메일 id: {}", sentMailIds.get(sentMailIds.size() - 1));
해당 방향으로 진행하겠습니다! 그러면 예외가 발생한 값은 수동으로 메일 발송 처리를 해주어야 할까요?

2024-10-18 15:23 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/dto/CreateMailRequestDto.java
> +								   int accountId) {
죄송합니다; 인텔리제이에서 보인 것과 다르게 커밋된 것 같아요

2024-10-18 15:23 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/infrastructure/MailJpaRepository.java
> +	@Query(value = """
외부 조인으로 변경하고 잘못된 형식이면 해당 메일은 삭제조치 하겠습니다!

2024-10-19 13:13 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/mail/infrastructure/MailJpaRepository.java
> +	@Query(value = """
메일 테이블에 이메일 컬럼을 추가하고, 메일 전송 시에 유저 테이블과 left join 하도록 하여, 최신 이메일로 보내도록 수정했습니다.

2024-10-21 11:57 UTC, VSFe approved these changes

2024-10-21 15:02 UTC, merged