Feature/hellozo0 Step 1. 이메일 발송 기능
C4-ComeTrue/C4-Preflight-2425 pull request #3
Opened 2024-10-18 12:03 UTC by hellozo0

## ERD
<img width="214" alt="스크린샷 2024-10-18 오후 8 19 45" src="https://github.com/user-attachments/assets/ad0d04ec-852d-4ce6-b678-26900238c88a">

- status는 PENDING, SUCCESS, FAIL, PERMANENT_FAIL
- 메일 전송 실패 횟수인 countRT

## 프로그래밍 요구사항
- 분단위 메일 전송을 위해 **CronJob** 을 사용해야 합니다. 어떤 방식으로 생성이 가능한지 확인해 주세요.
- 테이블에 들어가야 할 정보가 무엇이 있을까요? 잘 생각해 보세요.

## 구현 방법
### 메일 전송 요청 남기는 API-
- API 요청 Dto인 MailSchdulerRequest에서 최소 필요한 정보인 userId,email,content를 받습니다.
- mailLogging()에서 Dto 내용을 저장합니다.(메일 전송 상태는 PENDING인 상태로 세팅)

### Cron 스케줄러 _ mailSendScheduler()
- `@Scheduled(cron = "0 * * * * *")`를 통해 1분마다 백그라운드에서 돌아간다.
- MailLog 테이블에서 status가 FAIL,PENDING인것을 조회한다.

### Mail전송 _ handleMailSending()
- Spring의 메일 전송을 위한 JavaMailSender을 사용해 메일 전송 로직 구현
- @Async("customAsyncExecutor")를 통해 비동기적으로 메일 전송 가능
- 다만 이 부분에서 메일을 보낸 후 상태 값을 수정해야해서 조회후에 저장을 해야한다. 

> 고민되는 부분
> 아무리 비동기적으로 작동한다고 하더라도, 매번 또 조회를 해야하고 저장을 하는 부분에서의 트랜잭션들은 순차적으로 저장되는 것이 아닌가?

### AsyncConfig
- customAsyncExecutor 구현을 통해 메일 전송이 비동기적으로 갈 수 있도록 설정한다.
- 멀티 쓰레드 풀의 크기 설정(기본쓰레드 수 5, 최대 10)

### SchedularConfig
- 스케줄러를 비동기적으로 처리하도록 하는 설정이다.
- 스케줄러의 스레드 풀 크기를 CPU의 2배로 설정해서 다중 작업을 동시에 처리할 수 있도록 한다.

2024-10-18 14:06 UTC, VSFe requested changes
ㅁㅁ

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/config/AsyncConfig.java
> +@EnableAsync
해당 어노테이션이 두개 붙어있네요?

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/config/AsyncConfig.java
> +        executor.setMaxPoolSize(10);
(이건 어려우니, 나중에라도 꼭 생각해보세요.)
QueueSize를 미지정하셨는데, 그렇다면 10개 이상의 task가 인입되면 어떻게 동작할 것 같나요?

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/controller/request/MailSchedulerRequest.java
> +    String content
- 빈 내용이 들어와도 상관 없나요?
- null이 들어와도 상관 없나요?

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/controller/MailSchedulerController.java
> +    public void postMailScheduler(@RequestBody MailSchedulerRequest request) {
validation 어노테이션을 걸었는데, 정작 여기서 `@Valid` 를 안 쓰시네요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/MailLog.java
> +    @Column(name = "mial_log_id", nullable = false)
?

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/MailLogRepository.java
> +    List<MailLog> findMailLogsByStatusIn(@Param("statuses") List<MailStatus> statuses);
이런 쿼리는 굳이 `@Query` 를 사용하지 않아도, 본래 조건을 통해 조회해도 동일한 결과가 나옴이 보장되는지라...
굳이 사용할 필요가 없어보입니다.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/MailLogRepository.java
> +public interface MailLogRepository extends JpaRepository<MailLog,Integer> {
코드 스타일 컨벤션이 적용 안 된 것으로 보이네요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +    private static final String MAIL_SUBJECT = "계좌생성되었습니다";
띄 어 쓰 기 부 탁 드 릴 게 요

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        mailLogRepository.save(new MailLog(request.userId(), request.email(), MailStatus.valueOf("PENDING"), request.content(), Instant.now(),Instant.now(), 0));
`MailStatus.PENDING`을 쓰시죠

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        mailLogRepository.save(new MailLog(request.userId(), request.email(), MailStatus.valueOf("PENDING"), request.content(), Instant.now(),Instant.now(), 0));
사실, 기본값들을 빼면 결국 request에 있는 것들을 기반으로 만드는 만큼, 그냥 JPA Domain 객체에서 저걸 받아서 객체를 던지는걸 쓰시는게 나을 것 같아요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        mailLogRepository.save(new MailLog(request.userId(), request.email(), MailStatus.valueOf("PENDING"), request.content(), Instant.now(),Instant.now(), 0));
유저가 존재하지 않을 수 있는데, 그에 대한 처리가 없네요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +    @Async("customAsyncExecutor")
AsyncExecutor 가 1개이면 이름 생략 가능합니다.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +            mailLog.sendFail(MailStatus.FAIL, Instant.now(), mailLog.getCountRT()+1);
예외에 대한 이유를 알 수 있게, 로깅을 추가해 주세요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +    @Async("customAsyncExecutor")
어차피 분단위로 처리되는 Scheduled-Job 에서 처리가 되는데, (애초에 별도의 스레드로 돌아감)
이럴거면 굳이 `@Async`를 쓸 필요가 없어보여요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        MailLog mailLog = mailLogRepository.findById(form.mailLogId()).orElseThrow(() -> new EntityNotFoundException("MailLog not found"));
지금 구조가
- MailLog를 가져와서 MailForm 을 만듦
- 그 MailForm 을 다시 까서 MailLog를 조회함.

좀 이상하죠?

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/model/MailStatus.java
> +@RequiredArgsConstructor
필드가 없으므로...
`@RequiredArgsConstrcutor` 나 `@Getter`가 모두 필요하지 않습니다.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/MailLog.java
> +    public void sendFail(MailStatus status, Instant updateTime, Integer countRT){
`send~~` 느낌 보단 `update~~` 가 좀 더 나은 네이밍으로 보여요.

2024-10-18 14:06 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        List<MailLog> mailLogs = mailLogRepository.findMailLogsByStatusIn(Arrays.asList(MailStatus.PENDING, MailStatus.FAIL));
`List.of(MailStatus.PENDING, MailStatus.FAIL)`

2024-10-18 15:07 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/controller/request/MailSchedulerRequest.java
> +    String content
MailLog에서 content에 대한 부분에 대한 NotNull에 대한 조건을 걸지 않았어서 뺐었는데,

다시 생각해보니까 이메일의 대한 본문이 없는 메일은 없을테니 무조건 들어오는게 맞겠네요!
그리고 NotBlank도요!

2024-10-18 15:13 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/controller/MailSchedulerController.java
> +    public void postMailScheduler(@RequestBody MailSchedulerRequest request) {
미치고 빼먹었네요

2024-10-18 15:15 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/domain/MailLog.java
> +    @Column(name = "mial_log_id", nullable = false)
WOW 오타 죄송합니다

2024-10-18 15:22 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/domain/model/MailStatus.java
> +@RequiredArgsConstructor
제가 개념을 확실하게 안 알아보고 사용했네요 
사용하는 어노테이션의 원리 잘 찾아보고 사용하겠습니다!

2024-10-18 15:26 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/domain/MailLog.java
> +    public void sendFail(MailStatus status, Instant updateTime, Integer countRT){
updateSuccess, updateFail 로 할까 처음에 생각을 했는데 

그러면 상태값만 바뀌는걸로 오해하지 않을까? 생각했는데 update가 값의 특정부분을 수정하는의미에서 맞는거 같네요! 
지나친 생각은... 산으로 가는법 ~ 🥹

2024-10-18 15:53 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/config/AsyncConfig.java
> +@EnableAsync
질문에 대한 다변 기록 
@Configuration은 파일단위에 붙이고 @EnableAsync는 최상단에 붙이면된다 따라서 Application 단에 하나만 붙여줘도 되는것이다.!

2024-10-18 15:55 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        MailLog mailLog = mailLogRepository.findById(form.mailLogId()).orElseThrow(() -> new EntityNotFoundException("MailLog not found"));
질문에 대한 기록!

레이어를 옮기는 것도 아니고, 오히려 불필요한 작업이 더 필요하게 된 경우라 도메인 객체를 옮기는것이 더 효율적이다.
클린코드 아키텍쳐 등등 을 모두 적용할수는 없다! 더 효과적인 방법을 찾아 따라갈것

2024-10-18 16:20 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/config/AsyncConfig.java
> +        executor.setMaxPoolSize(10);
이부분은 공부해보고 질문이 있으면 그때 정리해서 한번더 코멘트 남기겠습니다!

2024-10-18 17:12 UTC, ZZAMBAs commented
합병되는 브랜치가 `main`으로 되어있어요!

2024-10-20 03:11 UTC, hellozo0 commented
엇 그렇네요... 감사합니다!!

2024-10-21 12:25 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/config/AsyncConfig.java
> +        executor.setMaxPoolSize(10);
2차 대용량 세미나를 들으면 나온 QueueSize 이야기..
threadPoolExecutor의 흐름도를 보면 이해가 더 잘 되는데 , 
1. corePoolSize가 꽉 찼다면 큐에 들어가게 된다.
2. 큐는 ArrayBlockedQueue와 LinkedBlockedQueue같은 것이 있는데, 
  -- Array같은 경우에는 큐가 가득 하게 되면 RejectedExecutionHandler가 데이터 처리를 못하게 되었을때 어떻게 처리할 것인지 담당하게 된다. 
  -- Linked같은 경우에는 특성상 데이터를 무한정 넣을 수 있음 따라서 모든 요청에 대한 처리를 할 수 있는것이다.
3. 그래서 ArayBlockedQueue 같은 경우에는 큐사이즈를 지정해줄 수 있다.
4. 하지만 LinkedBlockQueue 같은 경우에는 큐 사이즈를 지정할 필요가 없다. 하지만 아래의 코드 처럼 넣은 이유는 처음부터 queueSize만큼의 공간을 확보하는 개념으로 쓰는것이다.


```
threadPoolExecutor = new ThreadPoolExecutor(threadCount, threadCount, 0L, TimeUnit.MILLISECONDS,
			new LinkedBlockingQueue<>(queueSize),
			(r, executor) -> {
				try {
					executor.getQueue().put(r); //작업 그냥 큐에 집어 넣을거임 때려 박겠다  무.조.건 => 어떻게든 작업이 진행되야하니까
				} catch (InterruptedException e) {
					log.error(e.toString(), e);
					Thread.currentThread().interrupt(); //작업 그냥 큐에 집어 넣을거임 때려 박겠다  무.조.건 => 어떻게든 작업이 진행되야하니까
				}
			});
```

2024-10-21 12:32 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/config/AsyncConfig.java
> +        executor.setMaxPoolSize(10);
코드에서 초기 Pool Size 5, QueueSize 100, MaxPoolSize 10으로 세팅한대로 코드 수정했습니다 *

2024-10-21 16:24 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/repository/MailLogRepository.java
> +    List<MailLog> findMailLogsByStatusIn(@Param("statuses") List<MailStatus> statuses);
아핫 불필요한 쿼리문은 굳이 작성하지 않아도 된다.... 메모...

2024-10-21 16:27 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/repository/MailLogRepository.java
> +public interface MailLogRepository extends JpaRepository<MailLog,Integer> {
- JpaRepository, Repository 분리
- JpaRepository<MailLog, Long>  Integer -> Long 
적용... 요 부분 맞을까요? 적용했습니다!

2024-10-21 16:27 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +    private static final String MAIL_SUBJECT = "계좌생성되었습니다";
띄 어 쓰 기 접 수 완 료

2024-10-21 16:35 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +    @Async("customAsyncExecutor")
스케줄링에서도 별도의 스레드로 비동기 처리를 하는데 
굳이 @Async를 추가로 사용한 필요가 없다는 것... 

지금 중복이 되어 있어서 의미가 없겠네요...

2024-10-21 16:57 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/MailSchedulerService.java
> +        mailLogRepository.save(new MailLog(request.userId(), request.email(), MailStatus.valueOf("PENDING"), request.content(), Instant.now(),Instant.now(), 0));
```
public void mailLogging(MailSchedulerRequest request) {
        if (!userRepository.existsById(request.userId())) {
            throw new IllegalArgumentException("User ID " + request.userId() + " 이 존재하지 않습니다.");
        }
        mailLogRepository.save(new MailLog(request));
    }
```

2024-10-21 17:03 UTC, hellozo0 commented
5개의 숨겨진 코드리뷰 적용 완료.... --> 숨겨지는 것도 오늘 처음 알았다..

2024-10-22 12:57 UTC, VSFe approved these changes
LNTM

2024-10-22 13:15 UTC, merged