Feature/opixxx step2 PR
C4-ComeTrue/C4-Preflight-2425 pull request #4
Opened 2024-10-25 16:07 UTC by opixxx

- 특정 날짜의 통계를 강제로 집계하는 API
    - QueryExecuteTemplate 를 이용해서 많은 양의 Transaction 데이터를 1000개씩 가져와서 날짜 별로 그룹화 하여 일 단위 송금금액, 누적 송금금액을 계산해서 통계 데이터를 집계함
  
- 새벽 4시 전날 통계를 집계하는 스케줄러
    - 현재 시각의 1일 전의 데이터를 1000개씩 가져와서 일 단위 송금금액, 누적 송금금액을 계산해서 통계 테이터를 집계함

- 시작날짜, 종료날짜를 받아 통계 데이터를 조회

2024-10-26 10:20 UTC, VSFe requested changes

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistics/domain/Statistics.java
> +    public static Statistics of(LocalDate statisticsDate, Long totalRemittance, Long cumulativeRemittance, LocalDateTime createAt) {
of의 의미가 있나요? 생성자랑 차이가 없네요.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistics/service/StatisticsService.java
> +        QueryExecuteTemplate.<Transaction>selectAndExecuteWithCursorAndPageLimit(-1, 1000,
1000은 상수로 빼 주세요.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/util/QueryExecuteTemplate.java
> +     * 이 메서드는 테스트 용을 위한 메서드(많은 데이터를 다 조회할 순 없잖아)
ㅋㅋㅋ

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/transaction/domain/repository/TransactionJpaRepository.java
> +    AND DATE(t.transactionDate) <= :endDate
쿼리에 일관성이 없네요.
첫 쿼리는 동등조건인데, 페이징 조건이 걸린 쿼리는 갑자기 부등호를 쓰네요?
코드를 보는 다른 사람들 입장에서 혼선이 생길 수 있어보입니다.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/transaction/domain/repository/TransactionJpaRepository.java
> +    AND DATE(t.transactionDate) <= :endDate
파라미터 이름도 맞춰주세요.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistics/service/StatisticsService.java
> +        Map<LocalDate, List<Transaction>> map = transactionList.stream()
누적 송금금액이 중요한 값 아닐까요?
굳이 날짜를 일일히 map으로 만들 필요는 없어보입니다.
중간 집계 데이터가 다소 불필요한지라, 굳이 map으로 중간 aggregate를 할 필요도 없어보여요.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistics/service/StatisticsService.java
> +        if (statistics == null) {
1000개를 조회할 때 마다 save or update 를 호출하는 이유가 있나요?
어차피 집계가 중간에 실패하면 해당 데이터는 의미 없는 데이터라, 굳이 중간 결과를 저장할 필요가 없어보입니다.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistics/controller/StatisticsController.java
> +    public ResponseEntity<Void> getStatistics(@RequestParam int pageSize, @RequestParam @NotNull LocalDate date) {
메서드 이름이 조금 이상해보이네요.
마치 Resource를 가져오는 듯한 뉘앙스에요.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistics/controller/StatisticsController.java
> +    @GetMapping("/statistics")
`CREATED` 는 일반적으로 HttpMethod.GET에서 나올 것으로 예상하지 않아요.
데이터 적재 목적은 Body가 없다고 해도 POST가 낫습니다.

2024-10-26 10:38 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/statistics/controller/StatisticsController.java
> +    @GetMapping("/statistics")
시작날짜와 종료날짜사이의 통계를 가져오는 API였는데 CREATED를 했었네요,,,,
200 OK를 반환하고 통계 데이터를 반환하도록 수정했습니다.

2024-10-26 10:39 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/statistics/controller/StatisticsController.java
> +    public ResponseEntity<Void> getStatistics(@RequestParam int pageSize, @RequestParam @NotNull LocalDate date) {
수정하려다가 놓쳤네요 ㅠ 수정했습니다!

2024-10-26 10:45 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/statistics/service/StatisticsService.java
> +        QueryExecuteTemplate.<Transaction>selectAndExecuteWithCursorAndPageLimit(-1, 1000,
네 상수로 빼주는게 더 좋겠네요! 반영했습니다

2024-10-26 10:48 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/util/QueryExecuteTemplate.java
> +     * 이 메서드는 테스트 용을 위한 메서드(많은 데이터를 다 조회할 순 없잖아)
혼잣말을 하면서 코드를 짜다가 혼잣말을 적었네요,,,, ㅋㅋㅋㅋ

2024-10-26 13:23 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/transaction/domain/repository/TransactionJpaRepository.java
> +    AND DATE(t.transactionDate) <= :endDate
```java
    @Query("""
    SELECT t
    FROM Transaction t
    WHERE ((t.transactionDate > :transactionDate) OR (t.transactionDate = :transactionDate AND t.id > :id))
    AND DATE(t.transactionDate) = :endDate
    ORDER BY t.transactionDate ASC, t.id ASC
    LIMIT :size
    """)
    List<Transaction> findTransactionWithEndDateAndLastDate(
            @Param("endDate") LocalDate endDate,
            @Param("transactionDate") Instant transactionDate,
            @Param("id") int id,
            @Param("size") int size
    );
```

넵! 혼란을 줄 여지가 있네요 쿼리 조건과 파라미터 이름 수정했습니다.

2024-10-26 15:53 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/statistics/service/StatisticsService.java
> +        Map<LocalDate, List<Transaction>> map = transactionList.stream()
넘어온 데이터들 중 가령, 1/1, 1/2일 데이터가 섞여 들어올 경우를 생각해서 날짜별로 묶었었습니다. 이런 예시에서 어떻게 일별 송금금액을 계산할지 좀 더 고민해보겠습니다.

2024-10-26 15:54 UTC, opixxx commented on src/main/java/org/c4marathon/assignment/statistics/service/StatisticsService.java
> +        if (statistics == null) {
집계가 실패했을 때도 의미없는 통계 데이터가 저장되겠네요,, 1000개씩 모든 조회가 끝나고 한 번에 저장하도록 변경했습니다.

2024-10-27 01:41 UTC, VSFe approved these changes

2024-10-27 12:30 UTC, merged