Feature/hellozo0 Step 2. 송금 이력 통계화
C4-ComeTrue/C4-Preflight-2425 pull request #5
Opened 2024-10-25 19:01 UTC by hellozo0

## 프로그래밍 요구사항
1.  새로운 통계 테이블을 생성합니다. 일 단위 당일 전체 송금 금액, 해당 날짜 까지의 누적 송금 금액을 담도록 작성해 주세요.
2.   해당 테이블을 조회하는 API (시작 날짜와 종료 날짜를 받는) 도 개발이 필요합니다.
3.   일반적인 경우 새벽 4시 에 전날 통계 집계가 진행됩니다.
4.  필요 시 API를 통해 특정 날짜의 통계를 강제로 집계할 수 있어야 합니다.

## 프로그래밍 요구사항
### [API 1 : 특정 날짜의 통계를 강제로 집계]
```
처음의 구현 방향 
1. 해당 API는 세팅을 위해 처음에만 사용한다고 생각을 했다. 
2. 그래서 만약 이전의 값이 부분 채워져 있다거나 하는 상황을 고려하지 않아도 된다라는 생각에 endDate까지의 모든 값을 구하는 방향으로 생각했다.
3. 기존 로직
    - 첫날부터 endDate까지 모든 Transaction을 1000개씩 가져와서 Map에서 날짜를 기준으로 파싱하고 구분할 수 있도록 한다. 
    - 1000개씩 dailyAmount를 Map의 Key를 기준으로 누적합 하고, DB에 저장한다.
    - 다음 1000개에서는 DB에서 Key에 해당하는 날짜를 조회하고 누적합 하고 다시 DB에 저장한다. 

생긴 문제점
1. 그렇다 보니 매번 1000개씩 마다 Map으로 날짜 확인하고, save → find → update 하는 과정에서의 transaction이 너무 많아진다. 
    - 시간이 너무 오래걸림, 이유는 18000개의 데이터라고 하면 1000번씩 180번을 save. find 하는 과정이 반복된다. 
2. 그리고 만약 해당 DB의 초반 일부분이 채워져있다거나 하면 로직이 꼬이게 된다.
    - 값이 채워져 있어도 예외처리가 까다로워서 원하는 누적값이 나오지 않았다. 

그래서 생각한 부분
1. 기존의 endDate전까지의 모든 데이터를 조회하는 방법이 아니라, 하루치마다 쿼리를 조회한다.
2. 하루치마다 조회를 하니, 이미 구해둔 값이 있거나 하면 계산하지 않는다 
3. 일별누적금액 계산과 전체누적금액을 분리해서 작업

생각한 이점 
1. Map 굳이 사용안해도되고, save → find → update 과정이 없어짐
2. 그리고 날짜 마다 작업이 끝나게 되면 전체누적금액 에 대한 로직 수행으로 비교적 기능의 분리가 가능

결과
1. 이전보다 통계를 하는데 걸리는 수행시간이 줄어들었다.(체감상 10분 -> 1분)
2. 다른 API에서도 하루치마다 계산을 하니 함수의 재사용성이 용이해졌다. 
```
<img width="801" alt="스크린샷 2024-10-26 오전 3 35 25" src="https://github.com/user-attachments/assets/1788335e-09a2-42ef-9315-8efda52694b7">

### [API 2 : 시작 날짜와 종료 날짜 사이의 통계]
```
로직의 흐름  
- 해당 날짜 사이의 당일 금액과 누적금액 재계산하는 방향으로 구현 
- 예를 들어 1월 2일 부터 1월 5일까지의 값을 알고 싶다면 1월 1일에 해당하는 금액이 전체 누적금액에 들어가지 않도록 구현

고민했던 부분 
- API1과 똑같이 만약 start~end 사이에 값이 부분적으로 채워져 있다면 API1과 같이 문제가 생김

해결 방법
- 만약 비어 start ~ end 사이의 값중에 비어 있는 값이 있다면 end까지의 통계를 구하고 조회가 가능하도록 변경
```
<img width="799" alt="스크린샷 2024-10-26 오전 3 27 11" src="https://github.com/user-attachments/assets/4c415193-ec04-4653-ba7c-ee009e9dde68">

### [3 : 새벽 4시 전날 통계 집계 진행]
```
로직의 흐름 : 
	1. 하루전 날짜 알아내기
	2. transaction에 하루전 날짜꺼에 대한 일별금액만 계산 (API1에서 사용한 함수 재사용)
	3. 2일전 전체누적금액 + 하루전 일별금액 
```

2024-10-26 11:33 UTC, VSFe requested changes

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/controller/response/CumulativeAmountResponse.java
> +        @DateTimeFormat(pattern = "yyyy-MM-dd")
이건 아쉽게도 Response 에선 의도한대로 동작이 안 될 가능성이 높습니다.
(기본 형식이라 된 것 처럼 보였을 가능성이...)
Request/Response 에서 활용하기 위해선, `@JsonFormat` 을 알아보시는게 맞는 것 같아요.

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/controller/StatisticsController.java
> +    public ResponseEntity<List<CumulativeAmountResponse>> getCumulativeAmountRangeDate(@RequestParam @NotBlank @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate startDate, @RequestParam @NotBlank @Da
`@NotBlank`는 String 에서만 유효합니다.
https://github.com/hibernate/hibernate-validator/blob/main/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/NotBlankValidator.java

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/model/PageInfo.java
> +public record PageInfo<T>(
PageInfo 를 사용하는 것도 좋겠지만...
사실 여기서는 굳이 이걸 쓸 필요가 없어보여요.

통계 데이터의 특성상 아무리 많아봤자 데이터의 수가 많을 수 없거든요.
오히려 저라면 30일을 초과하는 범위를 조회하지 못하게 막아버릴 것 같습니다.

(수정하진 마세요. 앞으로 참고하시라는 의미입니다.)

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/TransactionRepository.java
> +		if(lastDateId == null){
포맷팅 적용 안하시고 코드 작성하신 것 같은데, IntelliJ의 포맷팅 관련 도구 찾아서 적용해 주세요.

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        // 1. 해당 날짜의 통계 테이블이 있으면 return
날짜가 없다고 계산을 하는게 의도가 맞는지 생각해 볼 필요는 있을 것 같아요.
API를 요청하는 입장에선 상당히 오랜 시간이 걸릴텐데, 그럴거면 그냥 요청에서 해당 날짜를 빼버리고, 빈 날짜의 값을 원하면 갱신을 하도록 유도하면 되지 않을까요?

이 API는 백오피스 API 라는 걸 기억해 주세요.

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        CumulativeAmount CA = cumulativeRepository.findByDate(endDate);
static final 변수가 아니라면 대문자 변수 이름은 지양해 주세요.
(사실 이것도 컨벤션 규칙입니다. 원래였으면 경고문이 떴어야겠네요.)

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        for (LocalDate currentDate = startDate.plusDays(1); !currentDate.isAfter(endDate); currentDate = currentDate.plusDays(1)) {
이건 오히려 while 문이 낫지 않을까요?

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +    private void calTransationAmount(LocalDate date){
API 명세에서도 "해당 날짜의" 통계를 계산하라고 했지, 전체 날짜의 통계를 전부 쌓으라고 하진 않았습니다.
테스트용으로 1970년 1월 1일 데이터가 하나 들어가면 로직이 심각하게 엉망이 될 것 같아요.

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        Instant earliestTransactionDate = transactionRepository.findEarliestTransactionDate(); //1월 1일
연도가 달라질 수 있지 않나요?

2024-10-26 11:33 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +            AtomicLong dailyAmount = calculateDailyAmount(currentDate);
이러면 그냥 long으로 리턴하는게 나아보이네요.

2024-10-26 11:44 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/controller/StatisticsController.java
> +    public ResponseEntity<List<CumulativeAmountResponse>> getCumulativeAmountRangeDate(@RequestParam @NotBlank @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate startDate, @RequestParam @NotBlank @Da
아앗...!  charSequence.toString().trim().length() > 0; 

charSeq를 비교하네요....ㅠㅠㅠ

2024-10-26 11:53 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/controller/response/CumulativeAmountResponse.java
> +        @DateTimeFormat(pattern = "yyyy-MM-dd")
https://jojoldu.tistory.com/361
해당 글을 보니까 Response Body에서 DateFormat이 제대로 안되는 경우가 있네요..! 
Get요청시에는 @DateTimeFormat
Post 요청, ResponseBody에서는 @JsonFormat  메모..끄덕끄덕...

2024-10-26 11:56 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/model/PageInfo.java
> +public record PageInfo<T>(
이부분이 사실 고민되었는데,,, 특강 들으면서 배운 내용?들 활용하려고 무작정 가져왔는데
사실 구현하면서 이게 오히려 로직이 더 까다로워지더라고요.. ㅠㅡㅠ 
고민을 했는데 어떻게 수정하면 좋을지 생각으로만 추후에 정리해보겠습니다!

2024-10-26 12:08 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/repository/TransactionRepository.java
> +		if(lastDateId == null){
설정을 안하고 작업을 했었네요.. https://github.com/naver/hackday-conventions-java/blob/master/rule-config/naver-intellij-formatter.xml 다운 받아서 추가 세팅 완료했습니다!

2024-10-26 12:19 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        for (LocalDate currentDate = startDate.plusDays(1); !currentDate.isAfter(endDate); currentDate = currentDate.plusDays(1)) {
그렇네요.... 아래처럼 간단하게 변경했습니다!

```
LocalDate currentDate = startDate.plusDays(1);
while (!currentDate.isAfter(endDate)) {
    CumulativeAmount currentCA = cumulativeRepository.findByDate(currentDate);
    long dailyAmount = currentCA.getDailyAmount();
    cumulativeTotal += dailyAmount;

    responses.add(new CumulativeAmountResponse(currentDate, currentDate, dailyAmount, cumulativeTotal));

    currentDate = currentDate.plusDays(1);
}
```

2024-10-26 12:23 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +            AtomicLong dailyAmount = calculateDailyAmount(currentDate);
여기서 long으로 리턴하고 해당 변수 사용하는 곳에서 바로 사용하는게 더 직관적이네요..! 

```
long dailyAmount = calculateDailyAmount(yesterday).get();
```

2024-10-26 12:45 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +    private void calTransationAmount(LocalDate date){
그러면 현재의 문제점이 
-  통계 값이 저장되어 있으면 PASS 하면서 계산을 하는데 이게 아니라, 무조건 통계 계산은 해야하는 거네요..!
-  그래서 날마다의 계산을 하는게 아니라 transaction의 date보다(주어진 입력값) 작은 값들을 매번 계산하는 로직..! 

... 이전에 구현했던 로직이 맞는 로직이였네요... 다시 돌아가서... 최적화할 수 있는 방법을 찾아보겠습니다.

2024-10-26 12:50 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        // 1. 해당 날짜의 통계 테이블이 있으면 return
없으면 강제 집계  API를 호출을 할 수 있도록 유도한다..! 
해당 API의 용도는 조회에 초점을 맞추고 해야하는 거였네요! .. 이부분을 먼저 반영하고 강제 호출 로직 수정해보겠습니다!

2024-10-26 17:05 UTC, hellozo0 commented on src/main/java/org/c4marathon/assignment/service/CumulativeAmountService.java
> +        // 1. 해당 날짜의 통계 테이블이 있으면 return
강제 호출 할 수 있도록 로직 수정했습니다! 이미 계산해둔 값이 있든 없든 덮는 방식으로 구현

2024-10-26 17:10 UTC, hellozo0 commented
백오피스의 기능을 다시 생각해서 다시 구현했습니다
1. 강제 통계 API  
    - 강제로 통계해서 이전에 값이 있더라도 뒤덮는 방식으로 수정
    - 배치개념으로 한번에 저장할 수 있도록 수정
2. 기간 사이의 통계값 조회 API 
    - 단순히 조회만 할 수 있도록 수정
    - 테이블에 값이 없다면 0으로 출력
3. 스케쥴러
    - 이전 날짜들의 값을 조회하거나 의존하지 않도록 매번 어제치의 통계와 어제까지의 누적 매번 새롭게 계산

2024-10-27 01:41 UTC, VSFe approved these changes

2024-10-27 12:30 UTC, merged