Feature/zzambas step2: 송금 이력 통계화
C4-ComeTrue/C4-Preflight-2425 pull request #6
Opened 2024-10-26 03:45 UTC by ZZAMBAs

집계 구현 방식은 다음과 같습니다.
1. 이미 집계된 통계가 있으면 그것을 반환.
2. 없으면 다음 중 하나를 수행
2-1. 바로 이전 통계 데이터를 가져와 누적 금액으로 저장, 통계 집계를 시작할 날짜를 설정.
2-2. 통계 데이터가 없다면 최초 트랜잭션 날짜를 집계 시작 날짜로 설정하고 누적 금액은 0으로 설정.
3. 집계 시작 시간부터 집계 끝 시간까지 6시간 단위로 분할, 각 시간 단위로 병렬 처리 및 벌크 연산
4. 모든 시간과 금액을 벌크 연산으로 삽입
* `/statistic/transaction/aggregate`로 통계 집계를 할 날짜를 정해 강제 집계가 가능합니다.
* `@Scheduled`를 통해 매 새벽 4시마다 한국 시간 기준 그 전날 통계를 집계합니다.

최대한 벌크 연산, 멀티스레드를 활용하여 통계 시간을 줄였습니다. 현재 데이터 기준 1분 안팎으로 전체 통계가 가능합니다.
### 이슈
`CustomThreadPoolExecutor`를 사용하려 했지만 자꾸 데이터가 안맞는 문제가 생겨서... 사용을 하지 않고 `Executors.newFixedThreadPool()`로 고정 스레드 풀을 생성해 그것을 이용하도록 했습니다. 그에 따라 에러는 없어졌습니다. 아직 이유를 찾지는 못했습니다.

2024-10-26 10:20 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/dto/TransactionStatisticResult.java
> +										 long dayAmount,
?

2024-10-26 10:51 UTC, VSFe requested changes

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/dto/TransactionStatisticResult.java
> +		long epochDay = transactionStatistic.getStatisticDate().getEpochSecond() / (60L * 60L * 24L);
그냥 처음부터 `LocalDate.ofInstant(...)` 을 쓰는게 낫지 않을까요?

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		Optional<TransactionStatistic> statisticOptional = statisticRepository.findCloseStatisticByStatisticDate(theDay);
이건 그냥 처음부터 그 날짜에 맞는 데이터를 들고오면 되지 않을까요?

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/domain/TransactionStatistic.java
> +	private Instant statisticDate;
사실 구분자는 굳이 Datetime을 유지할 필요가 없습니다.
검색 API 관점에서도 검색 대상 Column이 Datetime을 유지하면 너무 불편하겠죠?

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		if (statisticOptional.isPresent() && Objects.equals(statisticOptional.get().getStatisticDate(), theDay)) {
데이터가 잘못 산입되어 재집계를 해야하는 케이스도 분명히 있어서...
데이터가 있다고 무조건 return 하는건 좋지 않습니다.

또한, 저희가 API를 호출하는 목적은 "데이터 적재 요청" 이지, "결과 전달" 이 아니라는 점도 기억해 주세요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +			executorService.awaitTermination(20L, TimeUnit.MINUTES);
작업의 양이 많아진다면, 20분 이상을 집계할 수도 있어요.
awaitTermination의 시간을 조금 더 늘리는게 낫겠네요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +	private Instant getMidnightOfDay(Instant time) {
의도를 파악하기 상당히 어려워 보여요.
메서드에 주석을 추가해 주세요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +	private Instant getMidnightOfDay(Instant time) {
또한, 그냥 LocalDate로 바꾼 후 다시 instant 로 바꾸는게 코드 작성 입장에선 더 나아보여요.

```java
return time.atZone(ZoneId.systemDefault()).toLocalDate().toInstant();
```

현재 코드는 Instant 로만 로직을 구성하고 있는데, Instant는 시간대 정보가 없으므로 0시라고 생각할 수 있어도 대한민국 시간 기준이면 안 맞을 가능성이 높습니다.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		ExecutorService executorService = Executors.newFixedThreadPool(8);
ThreadPool 과 같이 무거운 객체는 Global 하게 선언하고, 사용 전에 초기화 하는 로직으로 전개하는게 좀 더 자연스러워 보여요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +			startTime = startTime.plusSeconds(SPLIT_SECONDS_PER_THREADS);
스레드의 갯수를 고려하지 않고 시간을 나누고 있는데요.
이렇다면 일반적인 threadPoolExecutor 보단 forkJoinPool 을 쓰는게 좀 더 나아보이네요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/global/util/CustomThreadPoolExecutor.java
> +		init();
작업을 수행할 때 마다 threadPoolExecutor를 초기화 하고 있네요?

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/domain/TransactionStatisticRepository.java
> +	public void saveAll(List<TransactionStatistic> transactionStatistics) {
Bulk Insert 가 좋긴 하지만, 옮기는 데이터가 그리 많지 않다면 솔직히 말해서 큰 메리트가 없습니다.
100년치 데이터를 삽입할게 아니라면 굳이? 라는 생각이 들어요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		Map<Instant, AtomicLong> statisticMap = new TreeMap<>(Comparator.comparing(Instant::getEpochSecond));
`ConcurrentHashMap`을 쓰는게 더 낫지 않을까요?
굳이 뭐 데이터를 막판에 순서대로 넣고 싶다면, 끝나고 key 기반으로 정렬하면 될 것 같은데요.

2024-10-26 10:51 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/transaction/infrastructure/TransactionJpaRepository.java
> +		ORDER BY t.transaction_date
정렬 조건이 잘못되었습니다.
페이징 쿼리임을 감안할 때, 중복된 값이 쿼링될 가능성이 있겠네요.

2024-10-26 11:12 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/dto/TransactionStatisticResult.java
> +										 long dayAmount,
죄송합니다. 레코드 정의할 때마다 이러네요 ㅠ

2024-10-26 11:15 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/dto/TransactionStatisticResult.java
> +		long epochDay = transactionStatistic.getStatisticDate().getEpochSecond() / (60L * 60L * 24L);
날짜 관련 클래스들의 메서드를 제대로 몰라서 그런 것 같습니다. 변경하겠습니다!

2024-10-26 11:17 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		Optional<TransactionStatistic> statisticOptional = statisticRepository.findCloseStatisticByStatisticDate(theDay);
저 부분은 통계 시작 지점을 정하려고 가장 가까운 데이터를 들고 오도록 했습니다. 예를 들어 1월 5일 통계를 내려고 할 때 1월 3일 데이터가 있으면 그 날 다음부터 통계를 집계합니다!

2024-10-26 11:18 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +			executorService.awaitTermination(20L, TimeUnit.MINUTES);
1시간으로 바꾸겠습니다!

2024-10-26 11:19 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/domain/TransactionStatistic.java
> +	private Instant statisticDate;
그러면 date로 하는 게 나은 걸까요?

2024-10-26 11:21 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +	private Instant getMidnightOfDay(Instant time) {
메서드들에 주석을 추가하고, 코드를 해당 코드로 수정하겠습니다!

2024-10-26 11:21 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +			startTime = startTime.plusSeconds(SPLIT_SECONDS_PER_THREADS);
각각의 차이를 이해하고 다시 작성하겠습니다..

2024-10-26 11:22 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/global/util/CustomThreadPoolExecutor.java
> +		init();
스레드 풀이 초기화되어 있지 않을 때 초기화하도록 수정하겠습니다!

2024-10-26 11:22 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		Map<Instant, AtomicLong> statisticMap = new TreeMap<>(Comparator.comparing(Instant::getEpochSecond));
적절한 자료구조로 리팩터링 하겠습니다

2024-10-26 11:29 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/domain/TransactionStatisticRepository.java
> +	public void saveAll(List<TransactionStatistic> transactionStatistics) {
오히려 코드만 더 길게 만든 거 같기도 합니다

2024-10-26 11:29 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/transaction/infrastructure/TransactionJpaRepository.java
> +		ORDER BY t.transaction_date
id 부분을 함께 적어주지 않아서가 맞을까요? 추가하겠습니다!

2024-10-26 17:49 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		Map<Instant, AtomicLong> statisticMap = new TreeMap<>(Comparator.comparing(Instant::getEpochSecond));
벌크 연산은 제거했습니다!

2024-10-26 17:49 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/domain/TransactionStatisticRepository.java
> +	public void saveAll(List<TransactionStatistic> transactionStatistics) {
벌크 연산은 제거했습니다!

2024-10-26 17:50 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/global/util/CustomThreadPoolExecutor.java
> +		init();
`execute()` 메서드에서는 `init()`을 제거했습니다.

2024-10-26 17:50 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +			executorService.awaitTermination(20L, TimeUnit.MINUTES);
그냥 계속 기다리게끔 했습니다!

2024-10-26 17:51 UTC, ZZAMBAs commented on src/main/java/org/c4marathon/assignment/statistic/application/TransactionStatisticService.java
> +		Optional<TransactionStatistic> statisticOptional = statisticRepository.findCloseStatisticByStatisticDate(theDay);
이제 이전 통계 데이터를 이용하지 않도록 했습니다.

2024-10-27 01:42 UTC, VSFe approved these changes

2024-10-27 12:30 UTC, merged