Feature/hodadako step1: 이메일 발송 기능
C4-ComeTrue/C4-Preflight-2425 pull request #8
Opened 2024-11-03 19:44 UTC by hodadako

## 구현사항
- 일반적으로, 계좌를 생성하게 되면 계좌 상품의 설명서가 메일로 발송됩니다.
- 저희는 해당 기능을 구현하기 전, 수동으로 메일을 전송하려고 합니다.
- 다만, 매번 일일히 메일을 보내게 되면 리소스의 낭비가 발생할 수 있으므로, 분단위로 메일을 자동 전송 하려고 합니다.
- 메일 전송 요청을 받아 메일 전송 요청을 남기고, 전송 후 결과를 남기는 테이블과 API를 생성해 주세요.

## 구현 설명

``EmailRecordService``
- ``save``
    - 전송할 이메일을 미리 저장하는 기능입니다.
    - 전송할 이메일의 초기 상태는 PENDING으로 저장합니다.

- ``sendEmail``
    - 현재 PENDING 상태인 모든 이메일 레코드를 조회하여 직접 처리하지 않고 이벤트를 넘기는 방식으로 구현했습니다.
    - 해당 이벤트는 ``EmailRecordEventListener``에서 받아서 처리합니다.
    - 각 이메일 레코드의 상태는 3번의 재시도 후 실패하면 ``FAILED``로 처리되고 정상적으로 보내지면 ``COMPLETED``로 변경합니다.
    - ``EmailRecordEvent``에 이메일을 미리 넣어두어 지연로딩이 일어나지 않도록 하였습니다.
    - 이메일 전송과 이메일 레코드 상태 변경을 비동기적으로 동작하도록 구현하였습니다.

2024-11-04 08:05 UTC, hodadako commented
착오가 있어서 이번 스텝이 제출이 좀 늦어졌는데 다음 스텝은 확인 해주시면 제 시간 안에 올리도록 하겠습니다.

그리고 지금 다시 확인하니 Commit Message 내역이 좀 들쭉 날쭉한 경향이 있는거 같아 이 부분도 다음 스텝에서는 좀 신경써서 작성해보도록 하겠습니다.

2024-11-07 08:29 UTC, VSFe requested changes

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/common/entity/BaseEntity.java
> +		BaseEntity other = (BaseEntity) o;
BaseEntity 를 상속하는 모든 객체는 id가 다름이 보장되나요?
다른 테이블이어도요?

그게 아니라면 equals()를 하위에 작성하는 건 좀 좋지 않아보여요.

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/event/EmailRecordEventListener.java
> +			log.error("이메일 전송에 실패했습니다.");
finally 블록에 들어있으면, 무조건 호출되지 않나요?

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/presentation/EmailRecordController.java
> +		URI uri = UriComponentsBuilder.fromUriString("http://localhost:8080/api/v1/email-records/" + saved.getId())
URL 변경을 고려하여, 필드로 주입받도록 구조를 변경해 주세요.

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/repository/EmailRecordReader.java
> +		return emailRecordRepository.findAllByEmailStatus(EmailStatus.PENDING);
PENDING 으로 검색되는 레코드의 수가 5-6천개라고 가정해 봅시다.
과연 findAll 을 쓰는게 좋을까요?

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/event/EmailRecordEventListener.java
> +		} catch (Exception e) {
FAILED 상태인 데이터의 재처리는 어떤 방식으로 하실 계획이신가요?

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/service/EmailRecordService.java
> +	@Transactional(readOnly = true)
만약 1분안에 처리가 안 되면 어떻게 될까요?

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/entity/EmailRecord.java
> +	private String subject;
글자수에 대한 검증이 입력 Parameter에는 없고, 여기에만 존재하네요.

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/entity/EmailRecord.java
> +	@Enumerated
`@Enumerated` 의 기본값은 `EnumType.ORDINAL` 입니다.
혹시 의도하신 부분일까요?
(사실 Ordinal 을 의도하셨다면 VARCHAR를 안 쓰셨겠지만...]

2024-11-07 08:29 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/dto/EmailRecordRequest.java
> +public class EmailRecordRequest {
Class로 감쌀 이유가 전혀 없어보이는데, 특별한 이유가 있을까요?
(Request와 Response를 묶기 위한 용도로 하는 분도 계시긴 한데..
 개인적으로는 딱히 좋아하진 않긴 하네요 ㅋㅋㅋ)

2024-11-08 08:27 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/entity/EmailRecord.java
> +	@Enumerated
``EnumType.STRING``을 넣으려는 의도였습니다ㅎㅎ,, 제가 빼먹은듯 하군요

2024-11-08 08:29 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/dto/EmailRecordRequest.java
> +public class EmailRecordRequest {
보초님이 말씀하신대로도 해봤고,, 지금과 같은 방식으로도 해봤는데 아직 어떤 방식이 낫다 라는 판단을 내리기는 좀 힘든거 같네요..

그러면 class 나 record 여러 개를 만드는걸 더 선호하는 편이신가요?

2024-11-09 03:24 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/common/entity/BaseEntity.java
> +		BaseEntity other = (BaseEntity) o;
수정해보겠습니다.

2024-11-09 03:24 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/event/EmailRecordEventListener.java
> +			log.error("이메일 전송에 실패했습니다.");
예외 발생 시에만 실패 상태로 돌리도록 수정하겠습니다~

2024-11-09 03:28 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/entity/EmailRecord.java
> +	private String subject;
유효성 검증에 추가해보겠습니다.

2024-11-09 03:57 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/service/EmailRecordService.java
> +	@Transactional(readOnly = true)
PENDING 상태인 엔티티가 다시 조회되어서 조회만 하고 처리하지 못한 레코드들이 다시 보여질 것 같습니다. 이 부분 고려해서 다시 작성해보겠습니다.

2024-11-09 04:05 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/repository/EmailRecordReader.java
> +		return emailRecordRepository.findAllByEmailStatus(EmailStatus.PENDING);
일단 해당 메서드에서 필요하지도 않는 전체 데이터를 가져오기 때문에 불필요한 조회라고 생각합니다. 

또한 전체 데이터를 한번에 어플리케이션에 올리기 때문에 불필요한 부하를 주게 되어서 OOM이 생길 수도 있지 않을까 생각해봅니다..

데이터베이스에서 결과를 일부만 가져와서 처리하는 방식으로 변경해보겠습니다.

2024-11-09 04:11 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/event/EmailRecordEventListener.java
> +		} catch (Exception e) {
다른 큐에 넣어서 이후에 한번에 처리하는 방식으로 해결하는 방법을 구현해보겠습니다.

2024-11-09 05:52 UTC, hodadako commented on src/main/java/org/c4marathon/assignment/domain/email_record/event/EmailRecordEventListener.java
> +		} catch (Exception e) {
다시 생각해보니까 이메일 전송이 실패한 경우에는 바로 재전송을 할 필요는 없지 않을까 싶습니다. 하루에 한번 스케쥴러를 돌려서 ``FAILED``상태인 데이터만 다시 이메일을 보내게끔 하면 되지 않을까 싶은데 혹시 어떻게 생각 하시나요??

2024-11-10 09:45 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/dto/EmailRecordRequest.java
> +public class EmailRecordRequest {
사실 이건 답이 없긴 한데 ㅋㅋ
저는 후자를 선호하긴 해요. (요건 컨벤션으로 미리 정의하면 좋을듯 하긴 한데, 제가 본 코드의 상당수가 후자라서 저도 자연스럽게 후자를 택하긴 해요. 코드 길어지는 것도 싫고...)

2024-11-10 09:45 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/domain/email_record/event/EmailRecordEventListener.java
> +		} catch (Exception e) {
이거는 답이 있는건 아니라서, 편한 방식으로 수행하시면 될듯 합니다.

2024-11-10 09:45 UTC, VSFe approved these changes

2024-11-11 11:36 UTC, merged