Feature/nyh365 step2
C4-ComeTrue/C4-Preflight-2425 pull request #9
Opened 2024-11-09 00:14 UTC by nyh365

## 구현 사항  
- 새로운 통계 테이블을 생성합니다.
- 일 단위 당일 전체 송금 금액, 해당 날짜까지의 누적 송금 금액을 담도록 작성해 주세요.
- 해당 테이블을 조회하는 API (시작 날짜와 종료 날짜를 받는) 도 개발이 필요합니다.
- 일반적인 경우 새벽 4시 에 전날 통계 집계가 진행되며, 필요 시 API를 통해 특정 날짜의 통계를 강제로 집계할 수 있어야 합니다.

## 특정 기간(시작 날짜, 종료 날짜)의 통계 데이터를 조회하는 API
- 입력으로 받은 기간의 통계 데이터를 반환합니다.

## 특정 날짜의 통계 강제 집계하는 API
- 통계 데이터(현재 기능에서는 당일 총 송금 금액, 누적 송금금액) 을 구하는 경우 DB의 집계 함수를 통해 구하는게 나을 것이라 판단했습니다. (속도 측면에서는 이점을 갖지만, DB 부하를 고려해봐야 할 것 같습니다.) 
- 따라서 DB 집계 함수를 이용하여 당일 총 송금 금액, 누적 송금금액을 구한 후 통계 테이블에 저장하는 식으로 구현했습니다.

## 새벽 4시 전날 통계 집계
- @scheduled를 통해 새벽 4시마다 통계 집계하도록 구현했습니다.
- 앞에서 구현했던 특정 날짜의 통계를 강제 집계하는 기능을 수행합니다.

2024-11-10 11:50 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/TransactionJpaRepository.java
> +	Long cumulativeRemittanceBeforeDate(@Param("date") Instant date);
해당 쿼리를 직접 돌려보셨나요?
```
SELECT COALESCE(SUM(t.amount), 0)
FROM `large-scale`.transaction t WHERE t.transaction_date < "2024-01-01"
```

흠... 저는 1분 32초가 나오는데요.
Heavy Query 에 대한 설정이 하나도 없어서 지금 상태로 이걸 호출하면 무조건 에러가 나야 정상일 것 같네요.

2024-11-10 11:56 UTC, VSFe requested changes
수정사항이 별로 없어보이긴 한데... 그래도 고민이 필요한 부분이 있어서 적어봤습니다.

2024-11-10 11:56 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/TransactionJpaRepository.java
> +	Long cumulativeRemittanceBeforeDate(@Param("date") Instant date);
해당 쿼리를 직접 돌려보셨나요?
```
SELECT COALESCE(SUM(t.amount), 0)
FROM `large-scale`.transaction t WHERE t.transaction_date < "2024-01-01"
```

흠... 저는 1분 32초가 나오는데요.
Heavy Query 에 대한 설정이 하나도 없어서 지금 상태로 이걸 호출하면 무조건 에러가 나야 정상일 것 같네요.

쿼리 개선을 진행하거나, 설정을 아예 분리시키는 등의 방식으로 구성 변경이 필요할 듯 하네요.

2024-11-10 11:56 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/StatisticJpaRepository.java
> +	List<Statistic> findAllByStatisticDateBetween(Instant startDate, Instant endDate);
이건 일반적인 Spring Data JPA 쿼리로도 만들 수 있지 않을까요?

2024-11-10 11:56 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/service/StatisticService.java
> +		Statistic statistic = statisticRepository.findByStatisticDate(startInstantDate, endInstantDate)
어차피 검색 레코드는 1건이라, upsert 쿼리로 날리던지, 데이터 삭제 후 재생성을 하던지 하는게 좀 더 자연스러울 것 같아요.
데이터가 없어도 setter 로직을 타게 하려고 하다보니까 다소 로직이 어색한 느낌이 있네요.

2024-11-10 14:50 UTC, nyh365 commented on src/main/java/org/c4marathon/assignment/service/StatisticService.java
> +		Statistic statistic = statisticRepository.findByStatisticDate(startInstantDate, endInstantDate)
지금 보니 어색한 부분이 있네요. 수정해서 반영하겠습니다.

2024-11-10 14:57 UTC, nyh365 commented on src/main/java/org/c4marathon/assignment/repository/TransactionJpaRepository.java
> +	Long cumulativeRemittanceBeforeDate(@Param("date") Instant date);
구현 당시 쿼리는 따로 돌려보지 않았습니다. 그 이유가 포스트맨 이용해서 API 호출할 때 해당 기능이 10초 안팎으로 걸려서 문제가 없을 거라 생각했습니다. 근데 말씀해 주신 대로 쿼리를 돌려보니 저도 1분 35~6초 정도 걸리네요. 왜 이러한 차이가 나는지 궁금합니다.

2024-11-12 15:02 UTC, nyh365 commented on src/main/java/org/c4marathon/assignment/repository/TransactionJpaRepository.java
> +	Long cumulativeRemittanceBeforeDate(@Param("date") Instant date);
pk를 이용하는 것으로 수정했습니다. pk가 클러스터링 인덱스로 지정되기 때문에 클러스터링 팩터가 좋아 조회 시 속도 측면에서 개선할 수 있을 것이라 생각했습니다. 실제 쿼리 돌려봤을 때 18초 정도 나오도록 수정했습니다.

2024-11-14 16:47 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/repository/TransactionJpaRepository.java
> +	Long cumulativeRemittanceBeforeDate(@Param("date") Instant date);
형식 깨진것만 좀 수정해주세요~

2024-11-14 16:47 UTC, VSFe approved these changes

2024-11-15 13:52 UTC, merged